global:
  exporter:
    port: port number
  auth:
    host: some host
    port: port number
    user: user name
    password: password

collector:
  type: pi
  metric:
    gauge_label:
      -
        name: owner
        type: task
        config_key: owner
      -
        name: repo
        type: task
        config_key: repo
      -
        name: file_system
        type: category
        category_id: "disk_space.mounted_on"

    gauge_list:
      -
        name: hpc_pi_disk_space_total_size_mb
        category_id: "disk_space.blocks.total_size_mb"
      -
        name: hpc_pi_disk_space_used_size_mb
        category_id: "disk_space.blocks.used_size_mb"
      -
        name: hpc_pi_disk_space_available_size_mb
        category_id: "disk_space.blocks.available_size_mb"

  category_list:
    -
      id: "disk_space.file_system"
      display_name: Filesystem
      label: Filesystem
      record_parser_class: RegexGroupParser
      record_parser_arguments:
        - 1
      value_saver_class: StringSaver
      value_saver_arguments: []
    -
      id: "disk_space.blocks.total_size_mb"
      display_name: "Total size (MB)"
      label: "1M-Blocks"
      record_parser_class: RegexGroupParser
      record_parser_arguments:
        - 2
      value_saver_class: NumberSaver
      value_saver_arguments: []
    -
      id: "disk_space.blocks.used_size_mb"
      display_name: "Used size (MB)"
      label: "Used"
      record_parser_class: RegexGroupParser
      record_parser_arguments:
        - 3
      value_saver_class: NumberSaver
      value_saver_arguments: []
    -
      id: "disk_space.blocks.available_size_mb"
      display_name: "Available size (MB)"
      label: "Available"
      record_parser_class: RegexGroupParser
      record_parser_arguments:
        - 4
      value_saver_class: NumberSaver
      value_saver_arguments: []
    -
      id: "disk_space.mounted_on"
      display_name: "Mounted on"
      label: "Mounted on"
      record_parser_class: RegexGroupParser
      record_parser_arguments:
        - 6
      value_saver_class: StringSaver
      value_saver_arguments: []


tasks:
  -
    owner: owner
    repo: repo
