language: python

python:
  - "3.6"
  - "nightly"

install:
  - pip install -e vendor/nwpc-hpc-model
  - pip install -e .
  - pip install -e .[test]

script:
  - pytest

notifications:
    email: false