global:
  exporter:
    port: port number
  auth:
    host: host
    port: port
    user: user
    password: password

category_list:
  -
    id: id
    display_name: display name
    label: label
    record_parser_class: parser class
    record_parser_arguments: array, parser arguments
    value_saver_class: value saver class
    value_saver_arguments: array, saver arguments

metrics_item:
  - item_id_one
  - item_id_two

identify_category_id: item_id